services:
  - type: web
    name: lastmatcha
    env: docker
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    docker:
      dockerfile: Dockerfile